### ISSUE TITLE
Option to not include pinned tabs in the sort action

### ISSUE THREAD

**Issue by KarlBlomquist** [pwhite2/simple-tab-sorter#6] opened 2020-06-02 14:40 UTC
Very nice add-on.   The main value being that it works with GreatSusp.

The only thing I would like to see (and will probably stop using the extension until it can do this), is the ability to exclude pinned tabs from the sort action.

Thanks.

**Comment by pwhite2** [comment] 2020-06-02 16:17
Thanks for the feedback, @KarlBlomquist, it's greatly appreciated.

TBH, I hadn't considered pinned tabs because, surprisingly, I can't remember the last time I pinned one. I'll be going on-call at work soon but, if this weekend's not too crazy, I'll take a stab at adding pinned tab support then.

Regards,
Peter

**Comment by pwhite2** [comment] 2020-06-02 21:28
@KarlBlomquist - I took a quick look at this, thinking it shouldn't be hard to implement, but wasn't able to reproduce the issue on MacOS with Google Chrome Version 83.0.4103.61.

When I pin tabs, regardless of my sort options, they are immediately relocated to the left-most side of my open tabs and sorting has no impact on them.

Please let me know what browser, version, and OS you're using so I can attempt to reproduce the behavior you're seeing and test the fix.

Thanks,
Peter

**Comment by KarlBlomquist** [comment] 2020-06-02 21:40
Thanks Peter.

Understood.   I personally use pinned tabs for my most commonly/frequently accessed sites.
I've uploaded an example of the behaviour here:  https://youtu.be/pIDqu2oRytY
Windows 10 Pro. 
Google Chrome is up to date
Version 83.0.4103.61 (Official Build) (64-bit)

Thanks a lot!

Cheers.

**Comment by KarlBlomquist** [comment] 2020-06-03 18:31
Hi Peter.

Sure.    I don't mind trying it out early.   I would never want to sort pinned tabs anyway, so the lack of the option does not matter to me anyway.

Cheers and thanks.

**Comment by pwhite2** [comment] 2020-06-03 18:52
Hi Karl,

You're quite welcome. I just pushed the hard-coded fix to https://github.com/pwhite2/simple-tab-sorter/tree/STS-6-exclude-pinned-tabs-from-sort. I'd appreciate it if you would confirm whether this behaves as expected after you uninstall the chrome store version and replace it with this version.

If this works as expected, I'll add a toggle to the options page and submit that version to the chrome store as version 0.3.0.

Cheers

**Comment by KarlBlomquist** [comment] 2020-06-03 20:55
Great!    Works exactly as hoped!     Thanks very much!

**Comment by pwhite2** [comment] 2020-06-03 21:07
Great, I'm glad to hear it, you are very welcome - thanks for raising a usability issue that I hadn't considered!

Please be sure to check the chrome webstore extension page for a version 0.3.0 update a few days after you get a github notification that this issues has been resolved - I want to make sure that you don't get pinned to this fix an miss out on any future changes...

**Comment by pwhite2** [comment] 2020-06-30 04:02
Hi @KarlBlomquist,

Apologies for the delay - work, suddenly, got much busier than expected...

I wanted to let you know that I've replaced the hard-coded fix I gave you with a new "Sort pinned tabs" Settings page option, which is disabled by default since I believe that would be the expected behavior based on your feedback and my thoughts on the matter.

I've merged the changes to master, cut the v0.3.0 release, and submitted the update to the Google Chrome Web Store so it should be available there within then next couple of days.

Thanks again for your feedback!

Cheers

**Closed by pwhite2** 2020-06-30 04:02 UTC
